version: 2
conda:
  environment: docs/environment.yml
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - ./docs/build.sh
