version: 2
conda:
  environment: environment.yml
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_build:
      - cd docs
      - jupyter lite build --config jupyterlite_config.json
