version: 2
conda:
  environment: envdocs/environment.yml
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    post_build:
      - cd docs
      - jupyter lite build --config jupyterlite_config.json
