name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - python==3.9.10
  - Jinja2==3.0.3
  - mkdocs==1.3.0
  - mkdocs-material==8.2.11
  - mamba
  - emsdk

  - pip:
      - jupyterlite
      - jupyterlite-sphinx
      - jupyterlite-xeus-python==0.5.1
      - empack
